# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pytorch-notes',
                'doc_host': 'https://vguerra.github.io',
                'git_url': 'https://github.com/vguerra/pytorch-notes',
                'lib_path': 'pytorch_notes'},
  'syms': {}}
