name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: vguerra/fastai-workflows/nbdev-ci@master
      with:
        use-requirements-file: true

